NAME: TanksAndTemples
N_POINTS: 16384
PC_PATH: dataset/TanksAndTemples/TanksAndTemples
IMG_PATH: dataset/TanksAndTemples/TanksAndTemples
TRAIN_PATH: dataset/TanksAndTemples/TanksAndTemples/train.csv
TEST_PATH: dataset/TanksAndTemples/TanksAndTemples/test.csv